# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [278]:
import numpy as np 

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [279]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [280]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [281]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)

print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [282]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [283]:
print(f'the exp of B is :\n{np.exp(B)}') #Exponentiate each number elementwise
print()
print(f'the minimum value is {np.min(B)}') #Calculate the minimum value in the whole matrix. 
# eller man kan använda B.min()
print()

print(f'the minimum value in each row is {B.min(axis=1)}') # Calculcate the minimum value in each row. 

print()
print(f'Calculcate the minimum value in each column is {B.min(axis=0)}') # Calculcate the minimum value in each column. 

print()
print(f'the index value for the minimum value in the whole matrix is {np.argmin(B)}')

print()
print(f'the index value for the minimum value in each row is {np.argmin(B, axis=1)}')


print()
print(f'the sum for all elements is {B.sum()}') # Calculate the sum for all elements.

print()
print(f'the mean for each column is {B.mean(axis=0)}') # Calculate the mean for each column

print()
print(f'the median for each column is {np.median(B, axis=0)}') #Calculate the median for each column
print()



the exp of B is :
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

the minimum value is 1

the minimum value in each row is [1 4 7]

Calculcate the minimum value in each column is [1 2 3]

the index value for the minimum value in the whole matrix is 0

the index value for the minimum value in each row is [0 0 0]

the sum for all elements is 45

the mean for each column is [4. 5. 6.]

the median for each column is [4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [284]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [285]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [286]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
# like in this example its returnin the row with index 1

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [287]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [288]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [289]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [290]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [291]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
# that is why in this example we gave -1 and its automatically calculate to 5 
# we could have give it (2,3,5) it would be the same result as (2,3,-1)
# now b is a two 2 dimensional arrays with 3 rows and 5 colums each.
b = a.reshape((2, 3, 5))

print(b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [292]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)


[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [293]:
v1 = np.array([1, 2, 3])
print(v1 + 1)
# the scalar 1 is stretched to become an array of same shape as v1
# the shapes are compatible for element-by-element addition

[2 3 4]


In [294]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
#  one dimensional array added to a two dimensional array results in broadcasting if number
# of 1-d array elements matches the number of 2-d array columns. which is in thiscase 2 elements in b = 2 columns in A

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [295]:
# a function to add or multiply matriser according to linear algebra rules 
import numpy as np


def add_multiply_matrices(matrise1 , matrise2 , operation):
     
     m1 = matrise1.shape[1]
     m02 = matrise2.shape[0]
     
    
     if  isinstance(matrise1 , np.ndarray) and isinstance(matrise2 , np.ndarray):
        
        if operation == 'multiply' and m1 != m02 :
           return 'Odefinerat pga olike dimensioner på matriser'
        elif operation == 'multiply':
                return matrise1 @ matrise2
        
        elif operation == 'add' and matrise1.shape != matrise2.shape: 
            return 'Odefinerat pga olike dimensioner på matriser'
        elif operation == 'add':
            return matrise1 + matrise2
        
        elif operation != 'multiply' or operation != 'add':
             return 'Choose either add or multiply.'
     else:
         return 'Odefinerat pga olike dimensioner på matriser'
     

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [296]:
#jag hade löst de inna jag visste att vi måste definera functionen det är därfor jag har inte använt den i detta .
# men det gjorde jag i nästa 
import numpy as np 
x = np.array([4,3])
print(x)
print()
# a
print(x.ndim)
print()

#b
print(x*5)
#c
print(x*3)
#d
print(x*5 + x*3)
#e
print(x*8)
#f
print(x*4 - x)
#g
g = (x.reshape(2,1))
print(g)

#h den här odefinerat due to mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 
print(g + x)
#i
y = np.linalg.norm(x)
y
print()
v = np.array([3,7,0,11]).reshape(4,1)
# 10.1.2
print(v)
print(v.shape)
print()
print(v*2)
print()
print(v*5 +v*2)
print()
print(v*4 -v*2)
print()
print(v.reshape(1,4))
print()
Z = np.linalg.norm(v)
print(Z)
print()
print()
#10.1.3
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])
print(v1)
print(v2)

#a
print()
V1 = np.linalg.norm(v1)
V2 = np.linalg.norm(v2)
print()
#b
V3 = V1 - V2
print(V3)



[4 3]

1

[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[[4]
 [3]]
[[8 7]
 [7 6]]

[[ 3]
 [ 7]
 [ 0]
 [11]]
(4, 1)

[[ 6]
 [14]
 [ 0]
 [22]]

[[21]
 [49]
 [ 0]
 [77]]

[[ 6]
 [14]
 [ 0]
 [22]]

[[ 3  7  0 11]]

13.379088160259652


[4 3 1 5]
[2 3 1 1]


3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [297]:
#10.2.1
print("A")
A = np.array([2,1,-1,1,-1,1]).reshape(2,3)
print(A)
print("B")
B = np.array([4,-2,1,2,-4,-2]).reshape(2,3)
print(B)
print("C")
C = np.array([1,2,2,1]).reshape(2,2)
print(C)
print("D")
D = np.array([3,4,4,3]).reshape(2,2)
print(D)
print("E")
E = np.array([1,2]).reshape(2,1)
print(E)
print("I")
I = np.array([1,0,0,1]).reshape(2,2)
print(I)
print()
print()
print()
#a
print("a)A*2")
print(A*2)
print("\nb)B - 2*A")
#b
print(add_multiply_matrices(B ,- A*2,"add"))
print("\nc)3C -2E")
#c
print(add_multiply_matrices(C*3, - E*2,"add"))
print("\nd)2D -3C")
#d
print(D*2 - C*3)
print("\ne)")
#e
print(add_multiply_matrices(D.T, D*2,"add"))
print("\nf)")
#f
print(add_multiply_matrices(C.T*2 ,- D.T*2,"add"))
print("\ng)")
#g
print(add_multiply_matrices(A.T,-B,"add"))

print("\nh)")
#h
print(add_multiply_matrices(A ,C,'multiply'))
print("\ni)")
#i
print(add_multiply_matrices(C ,D,'multiply'))
print("\nj)")
#j
print(add_multiply_matrices(C ,B,'multiply'))
print("\nk)")
#k
print(add_multiply_matrices(C ,I,'multiply'))
print("\nl)")
#l
print(add_multiply_matrices(A ,B.T,'multiply'))
print()

A
[[ 2  1 -1]
 [ 1 -1  1]]
B
[[ 4 -2  1]
 [ 2 -4 -2]]
C
[[1 2]
 [2 1]]
D
[[3 4]
 [4 3]]
E
[[1]
 [2]]
I
[[1 0]
 [0 1]]



a)A*2
[[ 4  2 -2]
 [ 2 -2  2]]

b)B - 2*A
[[ 0 -4  3]
 [ 0 -2 -4]]

c)3C -2E
Odefinerat pga olike dimensioner på matriser

d)2D -3C
[[3 2]
 [2 3]]

e)
[[ 9 12]
 [12  9]]

f)
[[-4 -4]
 [-4 -4]]

g)
Odefinerat pga olike dimensioner på matriser

h)
Odefinerat pga olike dimensioner på matriser

i)
[[11 10]
 [10 11]]

j)
[[  8 -10  -3]
 [ 10  -8   0]]

k)
[[1 2]
 [2 1]]

l)
[[5 2]
 [7 4]]



In [298]:
#10.2.2
A = np.array([2,3,4,5,4,1]).reshape(2,3)
A
print(add_multiply_matrices(A,A.T,"multiply"))

[[29 26]
 [26 42]]


In [299]:
#10.2.3
print("A")
A = np.array([1,2,2,4]).reshape(2,2)
print(A)
print("B")
B = np.array([2,1,1,3]).reshape(2,2)
print(B)
print("C")
C = np.array([4,3,0,2]).reshape(2,2)
print(C)
print()
X = print(add_multiply_matrices(A,B,"multiply"))

Y = print(add_multiply_matrices(A,C,"multiply"))
print(f"X = Y is True"if X == Y else False)


A
[[1 2]
 [2 4]]
B
[[2 1]
 [1 3]]
C
[[4 3]
 [0 2]]

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
X = Y is True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [300]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [301]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [302]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [303]:
##
